from playwright.sync_api import sync_playwright
from pathlib import Path
root=Path('/mnt/data/keys-with-simoni-react/public')
with sync_playwright() as p:
 browser=p.chromium.launch(headless=True,executable_path='/usr/bin/chromium',args=['--no-sandbox','--disable-dev-shm-usage'])
 page=browser.new_page(viewport={'width':1440,'height':1000},accept_downloads=True)
 errors=[];page.on('pageerror',lambda e:errors.append(str(e)))
 page.set_content('<html><head></head><body><div id="root"></div></body></html>')
 page.evaluate("Object.defineProperty(window, 'localStorage', {configurable:true,value:{getItem:function(k){return this[k]||null},setItem:function(k,v){this[k]=v},removeItem:function(k){delete this[k]}}})")
 page.add_style_tag(content=(root/'styles.css').read_text().split('\n',1)[1])
 for script in ['vendor/react.production.min.js','vendor/react-dom.production.min.js','vendor/jszip.min.js','vendor/hooks-shim.js','schema.js','demo-data.js','app.js']:
  page.add_script_tag(content=(root/script).read_text())
 print('Dashboard:',page.locator('.metric').count(),'metrics')
 page.locator('.sidebar .nav-item',has_text='Clients').click()
 print('Clients:',page.locator('.data-table tbody tr').count(),'rows')
 page.screenshot(path='/mnt/data/keys_with_simoni_react_clients.png',full_page=True)
 page.get_by_role('button',name='Add client').first.click()
 print('Editor title:',page.locator('.drawer-top h2').inner_text())
 page.locator('#full_name').fill('Test Buyer')
 page.locator('#phone').fill('+971 50 010 1010')
 page.get_by_role('button',name='Create record').click()
 print('Added client exists:',page.get_by_text('Test Buyer').count())
 print('Toast:',page.locator('.toast').inner_text() if page.locator('.toast').count() else 'none')
 page.locator('input[placeholder="Search records..."]').fill('Test Buyer')
 print('Filtered rows:',page.locator('.data-table tbody tr').count())
 page.locator('.sidebar .nav-item',has_text='Client desk').click()
 page.screenshot(path='/mnt/data/keys_with_simoni_react_client_desk.png',full_page=True)
 print('Client desk title:',page.locator('.profile-hero h2').inner_text())
 page.locator('.sidebar .nav-item',has_text='Deals').click()
 page.locator('.data-table tbody tr').first.click()
 print('Deal detail:',page.locator('.detail-drawer').count())
 page.locator('.detail-drawer .drawer-top button').click()
 page.get_by_role('button',name='Data & export').click()
 print('Export menu:',page.get_by_text('Export 17-sheet Excel').count())
 with page.expect_download(timeout=15000) as dl:
  page.get_by_text('Export 17-sheet Excel').click()
 d=dl.value
 d.save_as('/mnt/data/keys_with_simoni_ui_export.xlsx')
 print('Excel downloaded:',d.suggested_filename)
 print('Runtime errors:',errors)
 browser.close()
