from pathlib import Path
from playwright.sync_api import sync_playwright
from PIL import Image, ImageDraw
import json, tempfile, threading, http.server, socketserver
root=Path('/mnt/data/keys-with-simoni-react/public')
img=Path('/mnt/data/keys-with-simoni-react/tests/test_photo.jpg')
im=Image.new('RGB',(640,400),'#d8e5df'); d=ImageDraw.Draw(im);d.rectangle((80,100,550,350),fill='#6b958c');d.rectangle((270,60,440,280),fill='#c0ab7f');im.save(img,quality=75)
class Quiet(http.server.SimpleHTTPRequestHandler):
 def log_message(self,*args): pass
 def __init__(self,*args,**kwargs):super().__init__(*args, directory=str(root), **kwargs)
with socketserver.TCPServer(('127.0.0.1',0),Quiet) as server:
 threading.Thread(target=server.serve_forever,daemon=True).start()
 url=f'http://127.0.0.1:{server.server_address[1]}/'
 with sync_playwright() as p:
  browser=p.chromium.launch(headless=True,executable_path='/usr/bin/chromium',args=['--no-sandbox','--disable-dev-shm-usage'])
  page=browser.new_page(viewport={'width':1440,'height':960},accept_downloads=True)
  errors=[]; page.on('pageerror',lambda e:errors.append(str(e)))
  page.set_content('<html><head></head><body><div id="root"></div></body></html>')
  page.evaluate("Object.defineProperty(window, 'localStorage', {configurable:true,value:{getItem:function(k){return this[k]||null},setItem:function(k,v){this[k]=v},removeItem:function(k){delete this[k]}}})")
  page.add_style_tag(content=(root/'styles.css').read_text().split('\n',1)[1])
  for script in ['vendor/react.production.min.js','vendor/react-dom.production.min.js','vendor/jszip.min.js','vendor/hooks-shim.js','schema.js','demo-data.js','app.js']:
   page.add_script_tag(content=(root/script).read_text())
  page.wait_for_selector('.sidebar .nav-item')
  page.locator('.sidebar .nav-item',has_text='Properties').click()
  page.wait_for_selector('.modern-property-card')
  print('Initial property count:',page.locator('.modern-property-card').count())
  page.screenshot(path='/mnt/data/Keys_with_Simoni_v1_2_Properties_Light.png',full_page=True)
  page.locator('.theme-switch').click()
  print('Theme after toggle:',page.evaluate('document.documentElement.dataset.theme'))
  page.screenshot(path='/mnt/data/Keys_with_Simoni_v1_2_Properties_Dark.png',full_page=True)
  page.locator('.theme-switch').click()
  page.locator('.modern-property-card').first.click()
  page.wait_for_selector('.detail-drawer')
  print('Empty media placeholder:',page.locator('.detail-drawer .media-placeholder').count())
  page.get_by_role('button',name='Add property photos').click()
  print('After add photo editor open:',page.locator('.editor-drawer').count(),'errors:',errors)
  page.wait_for_selector('.editor-drawer',timeout=5000)
  print('Editor gallery upload input:',page.get_by_label('Upload property photos').count())
  page.get_by_label('Upload property photos').set_input_files(str(img))
  page.wait_for_selector('.editor-photo img',timeout=10000)
  print('Photo added:',page.locator('.editor-photo img').count())
  page.locator('.amenity-chip-list button',has_text='Balcony').click()
  page.locator('#property_description').fill('Bright two-bedroom property with landscaped views and premium finishes.')
  page.locator('#key_selling_points').fill('High floor • Flexible viewing • Vacant on transfer')
  page.get_by_role('button',name='Save changes').click()
  page.wait_for_timeout(500)
  print('Image card preview:',page.locator('.modern-property-card .property-cover-img').count())
  page.locator('.modern-property-card').first.click()
  page.wait_for_selector('.detail-drawer .media-photo-hero img')
  print('Detail photo:',page.locator('.media-photo-hero img').count(),'Amenity:',page.locator('.detail-drawer .amenity-tags').inner_text()[:100])
  page.screenshot(path='/mnt/data/Keys_with_Simoni_v1_2_Property_Details.png',full_page=True)
  page.locator('.detail-drawer .drawer-top button').click()
  print('Photo saved to storage:', 'media_photos' in page.evaluate("localStorage.getItem('kws-crm-v1')"))
  page.get_by_role('button',name='Data & export').click()
  with page.expect_download() as dl:page.get_by_text('Full backup with photos (JSON)').click()
  dest='/mnt/data/Keys_with_Simoni_v1_2_Test_Backup.json';dl.value.save_as(dest)
  obj=json.loads(Path(dest).read_text());print('Backup media included:',len(obj['data']['Properties'][0].get('media_photos',[])),'format:',obj['format'])
  page.get_by_role('button',name='Data & export').click()
  with page.expect_download() as dl:page.get_by_text('Export 17-sheet Excel').click()
  dest_x='/mnt/data/Keys_with_Simoni_v1_2_Test_Export.xlsx';dl.value.save_as(dest_x)
  print('Excel saved:',Path(dest_x).stat().st_size,'bytes')
  page.set_viewport_size({'width':390,'height':844})
  page.screenshot(path='/mnt/data/Keys_with_Simoni_v1_2_Properties_Mobile.png',full_page=True)
  over=page.evaluate('document.documentElement.scrollWidth > window.innerWidth+1')
  print('Mobile horizontal overflow:',over)
  print('JavaScript errors:',errors)
  browser.close()
