from playwright.sync_api import sync_playwright
from pathlib import Path
import zipfile, json
root=Path('/mnt/data/keys-with-simoni-react/public')
with sync_playwright() as p:
 browser=p.chromium.launch(headless=True,executable_path='/usr/bin/chromium',args=['--no-sandbox','--disable-dev-shm-usage'])
 page=browser.new_page(viewport={'width':1200,'height':900},accept_downloads=True)
 errors=[];page.on('pageerror',lambda e:errors.append(str(e)))
 page.set_content('<html><body><div id="root"></div></body></html>')
 page.evaluate("Object.defineProperty(window,'localStorage',{configurable:true,value:{getItem:function(k){return this[k]||null},setItem:function(k,v){this[k]=v},removeItem:function(k){delete this[k]}}})")
 page.add_style_tag(content=(root/'styles.css').read_text())
 for s in ['vendor/react.production.min.js','vendor/react-dom.production.min.js','vendor/jszip.min.js','vendor/hooks-shim.js','schema.js','demo-data.js','app.js']:
  page.add_script_tag(content=(root/s).read_text())
 page.locator('.sidebar .nav-item',has_text='Properties').click()
 page.get_by_role('button',name='Add property',exact=True).click()
 id=page.locator('#property_id');print('Add property ID input:',id.get_attribute('type'),'value:',id.input_value())
 page.locator('#listing_title').fill('Contemporary Seaside Villa')
 page.locator('#sale_rental').select_option('Holiday home')
 page.locator('#property_type').select_option('Villa')
 page.locator('#price_annual_rent_aed').fill('2700')
 page.locator('#bathrooms').fill('4')
 page.locator('#parking_spaces').fill('2')
 page.locator('#property_description').fill('Sea view villa with a private pool.')
 page.get_by_label('Upload floor plans').set_input_files({'name':'plan.png','mimeType':'image/png','buffer':Path('/mnt/data/keys-with-simoni-react/tests/test_photo.jpg').read_bytes()})
 page.wait_for_selector('.editor-plan')
 page.locator('.amenity-chip-list button',has_text='Private pool').click()
 page.get_by_role('button',name='Create record').click()
 page.wait_for_selector('.modern-property-card')
 print('New property in list:',page.get_by_text('Contemporary Seaside Villa').count())
 page.get_by_role('button',name='Data & export').click()
 with page.expect_download() as dl:page.get_by_text('Export 17-sheet Excel').click()
 out='/mnt/data/Keys_with_Simoni_v1_2_Excel_Export_Test.xlsx';dl.value.save_as(out)
 with zipfile.ZipFile(out) as z:
  data=z.read('xl/worksheets/sheet5.xml').decode();print('Excel contains new listing & new fields:', 'Contemporary Seaside Villa' in data, 'Property description' in data)
 page.get_by_role('button',name='Data & export').click()
 with page.expect_download() as dl:page.get_by_text('Full backup with photos (JSON)').click()
 saved='/mnt/data/Keys_with_Simoni_v1_2_Complete_Backup_Test.json';dl.value.save_as(saved)
 backup=json.loads(Path(saved).read_text());print('Backup property and floor plan:',backup['data']['Properties'][0]['listing_title'],len(backup['data']['Properties'][0].get('media_floorplans',[])))
 # test restoring from backup after clearing current database
 page.get_by_role('button',name='Data & export').click()
 page.once('dialog',lambda dialog:dialog.accept())
 page.get_by_text('Start with blank CRM').click()
 print('Blank properties count:',page.locator('.modern-property-card').count() if page.get_by_text('Properties').count() else 'dashboard')
 page.get_by_role('button',name='Data & export').click()
 page.get_by_text('Restore full backup (JSON)').click()
 page.once('dialog',lambda dialog:dialog.accept())
 page.locator('input[accept=".json,application/json"]').set_input_files(saved)
 page.wait_for_timeout(250)
 print('Restored property count:',page.locator('.modern-property-card').count(),'restored property visible:',page.get_by_text('Contemporary Seaside Villa').count())
 page.locator('.modern-property-card').first.click()
 print('Plan visible on detail:',page.locator('.detail-drawer .floorplan-list a').count(),'amenity:',page.locator('.detail-drawer .amenity-tags').inner_text()[:80])
 print('JS errors:',errors)
 browser.close()
