from playwright.sync_api import sync_playwright
from pathlib import Path
s=Path('/mnt/data/Keys_with_Simoni_CRM_v1_2_Open_in_Browser.html').read_text()
with sync_playwright() as p:
 b=p.chromium.launch(headless=True,executable_path='/usr/bin/chromium',args=['--no-sandbox','--disable-dev-shm-usage'])
 page=b.new_page(viewport={'width':1440,'height':960})
 errs=[];page.on('pageerror',lambda e:errs.append(str(e)))
 page.set_content(s,wait_until='domcontentloaded')
 print('ONE-FILE APPLICATION STARTS:',page.locator('.sidebar .nav-item').count(),'navigation items')
 page.locator('.sidebar .nav-item',has_text='Properties').click()
 print('DEFAULT LISTINGS:',page.locator('.modern-property-card').count())
 page.screenshot(path='/mnt/data/Keys_with_Simoni_CRM_v1_2_Design_Preview.png')
 page.locator('.purpose-pill',has_text='Holiday homes').click()
 print('HOLIDAY HOME FILTER:',page.locator('.modern-property-card').count())
 page.locator('.purpose-pill',has_text='For rent').click()
 print('RENTAL FILTER:',page.locator('.modern-property-card').count())
 page.locator('.purpose-pill',has_text='All listings').click()
 page.locator('.theme-switch').click()
 print('DARK THEME:',page.evaluate('document.documentElement.dataset.theme'))
 page.screenshot(path='/mnt/data/Keys_with_Simoni_CRM_v1_2_Design_Dark.png')
 page.set_viewport_size({'width':390,'height':844})
 print('MOBILE OVERFLOW:',page.evaluate('document.documentElement.scrollWidth > window.innerWidth+1'))
 page.screenshot(path='/mnt/data/Keys_with_Simoni_CRM_v1_2_Design_Mobile.png')
 print('RELEASE JS ERRORS:',errs)
 b.close()
