const OPTIONS = {
  'Lead stage': [
    'New',
    'Contacted',
    'Qualified',
    'Viewing',
    'Negotiation',
    'Documentation',
    'Closed',
    'Lost',
    'On hold',
  ],
  'Deal stage': [
    'New',
    'Qualified',
    'Viewing',
    'Offer',
    'Negotiation',
    'Documentation',
    'Completed',
    'Lost',
    'Cancelled',
    'On hold',
  ],
  'Listing status': [
    'Available',
    'Under offer',
    'Rented',
    'Sold',
    'On hold',
    'Unavailable',
    'Withdrawn',
  ],
  'Task status': ['Open', 'In progress', 'Completed', 'Cancelled'],
  'Viewing status': ['Scheduled', 'Confirmed', 'Completed', 'Cancelled', 'No-show'],
  'Buy / rent': ['Buy', 'Rent'],
  'Sale / rental': ['Sale', 'Rental', 'Holiday home'],
  Emirate: [
    'Dubai',
    'Abu Dhabi',
    'Sharjah',
    'Ajman',
    'Ras Al Khaimah',
    'Fujairah',
    'Umm Al Quwain',
  ],
  'Property type': [
    'Apartment',
    'Studio',
    'Villa',
    'Townhouse',
    'Penthouse',
    'Duplex',
    'Loft',
    'Serviced apartment',
    'Hotel apartment',
    'Office',
    'Retail',
    'Shop',
    'Showroom',
    'Warehouse',
    'Industrial',
    'Commercial building',
    'Residential building',
    'Plot',
    'Land',
    'Other',
  ],
  'Ready / off-plan': ['Ready', 'Off-plan'],
  'Price basis': ['Total price', 'Annual', 'Monthly', 'Weekly', 'Nightly'],
  Priority: ['High', 'Medium', 'Low'],
  'Client type': ['Buyer / tenant', 'Buyer', 'Tenant', 'Seller', 'Landlord', 'Investor', 'Other'],
  'Finance type': ['Cash', 'Mortgage', 'Self-funded', 'Other'],
  'Mortgage stage': ['Not started', 'In progress', 'Pre-approved', 'Approved', 'Not applicable'],
  'Funds confirmed': ['Yes', 'No', 'Partially', 'Unknown'],
  'Decision maker': ['Yes', 'No', 'Joint'],
  'Buying / moving urgency': [
    'Immediately',
    'Within 30 days',
    'Within 60 days',
    'Within 90 days',
    'Exploring',
  ],
  'Lead source': [
    'Referral',
    'Instagram',
    'TikTok',
    'Website',
    'Property Finder',
    'Bayut',
    'Facebook',
    'LinkedIn',
    'Walk-in',
    'Cold outreach',
    'Other',
  ],
  'Preferred channel': ['WhatsApp', 'Phone', 'Email', 'SMS'],
  Channel: ['WhatsApp', 'Phone', 'Email', 'SMS', 'In-person', 'Other'],
  'Contact permission': ['Yes', 'No', 'Unknown'],
  'Relationship status': ['Active', 'Past client', 'Referral partner', 'Inactive', 'Investor'],
  'Pipeline type': [
    'Off-plan sale',
    'Secondary sale',
    'Residential rental',
    'Commercial sale',
    'Commercial rental',
    'Landlord acquisition',
  ],
  'Fee basis': ['Percentage', 'Fixed'],
  'Document status': ['Pending', 'In progress', 'Complete', 'Missing'],
  'Contact type': [
    'Owner',
    'Landlord',
    'Client',
    'Developer',
    'Broker',
    'Partner',
    'Supplier',
    'Other',
  ],
  Furnishing: ['Furnished', 'Unfurnished', 'Part-furnished'],
  Direction: ['Inbound', 'Outbound'],
  'Action status': ['Open', 'In progress', 'Completed', 'Cancelled'],
  'Objection category': [
    'Budget',
    'Price',
    'Location',
    'Financing',
    'Timing',
    'Competition',
    'No response',
    'Property quality',
    'Changed plans',
    'Other',
  ],
  'Lost reason': [
    'Budget',
    'Price',
    'Location',
    'Financing',
    'Timing',
    'Competition',
    'No response',
    'Property quality',
    'Changed plans',
    'Other',
  ],
  'Lost / cancelled reason': [
    'Budget',
    'Price',
    'Location',
    'Financing',
    'Timing',
    'Competition',
    'No response',
    'Property quality',
    'Changed plans',
    'Other',
  ],
  'Recontact possible': ['Yes', 'No', 'Unknown'],
  'Touchpoint type': [
    'Post-sale check-in',
    'Lease renewal',
    'Investor update',
    'Referral request',
    'Birthday / milestone',
    'General check-in',
  ],
  'Client relationship': ['New', 'Active', 'Past client', 'Investor', 'Inactive'],
  'Referral outcome': ['Not yet', 'Referral received', 'Meeting booked', 'Converted', 'None'],
  'Client response': [
    'Interested',
    'Pending',
    'Not interested',
    'Viewing requested',
    'Negotiating',
  ],
  'Rental cheques': ['1', '2', '3', '4', '6', '12'],
};

const computedByModule = {
  Clients: [
    'Duplicate contact',
    'Last contact auto',
    'Next follow-up auto',
    'Follow-up status auto',
    'Record check',
    'Lead tier auto',
  ],
  Deals: [
    'Gross fee AED ex VAT',
    'After partner AED',
    'Your expected fee AED',
    'Your earned fee AED',
    'Outstanding AED',
    'Payment status',
    'Record check',
  ],
  Properties: ['Availability review', 'Permit date alert', 'Record check'],
  'Follow-ups': [
    'Due-date alert',
    'Client name auto',
    'Property title auto',
    'Record check',
    'Task order auto',
  ],
  Viewings: ['Client name auto', 'Property title auto', 'Record check'],
  Shortlist: ['Client name auto', 'Property title auto', 'Record check'],
  Payments: ['Total received AED', 'Record check'],
  'Interaction log': ['Client name auto', 'Record check auto'],
  'Client care': ['Client name auto', 'Reminder auto', 'Record check auto'],
  Contacts: ['Record check'],
  Expenses: ['Record check'],
};

const numRegex =
  /\b(AED|sq ft|budget|bedrooms|bathrooms|parking spaces|amount|cheques|fee rate|share %|score \/|deposit|nights|guests)\b/i;

const dateRegex =
  /(date|\bdue\b|expires|expiry|last verified|received on|contacted on|added on|next contact|last contact|next follow-up|last qualified|closed on|re-engage|opened|earned|payment due|available from)/i;

const longRegex =
  /(notes|summary|criteria|objection|commitment|description|feedback|blocker|interests|amenities|selling points|instructions)/i;

export { OPTIONS, computedByModule, numRegex, dateRegex, longRegex };
