const nav = [
  {
    header: 'WORKSPACE',
    items: [
      ['Dashboard', 'grid'],
      ['Client desk', 'search'],
      ['CRM insights', 'sparkle'],
    ],
  },
  {
    header: 'SALES & RELATIONSHIPS',
    items: [
      ['Leads', 'target'],
      ['Clients', 'users'],
      ['Contacts', 'person'],
      ['Properties', 'building'],
      ['Deals', 'briefcase'],
      ['Follow-ups', 'calendar'],
      ['Viewings', 'home'],
      ['Shortlist', 'target'],
      ['Interaction log', 'chat'],
      ['Client care', 'heart'],
    ],
  },
  {
    header: 'FINANCE & ANALYTICS',
    items: [
      ['Payments', 'wallet'],
      ['Expenses', 'money'],
      ['Date search', 'clock'],
      ['Performance', 'chart'],
    ],
  },
  { header: 'RESOURCES', items: [['Guide', 'help']] },
];

const labels = {
  Dashboard: 'Overview',
  Leads: 'Leads & sources',
  Deals: 'Deals & commissions',
  Clients: 'Clients & requirements',
  Contacts: 'Owners & contacts',
  Properties: 'Property portfolio',
  'Follow-ups': 'Follow-ups & daily tasks',
  Viewings: 'Viewings & feedback',
  Payments: 'Commission receipts',
  Expenses: 'Business expenses',
  Shortlist: 'Property shortlist',
  'Client desk': 'Client search & matching',
  'Date search': 'Search by date',
  Performance: 'Performance & targets',
  'Interaction log': 'Communication history',
  'Client care': 'Client relationships',
  'CRM insights': 'CRM intelligence',
  Guide: 'Getting started',
};

const descriptions = {
  Leads: 'Track enquiries, contact details, and where every lead came from.',
  Clients: 'Manage relationships, qualification, budgets, and conversion.',
  Contacts: 'A single record for every landlord, client, owner, developer, and broker.',
  Properties: 'Organize listings, pricing, availability, and permit tracking.',
  Deals: 'Manage each transaction from offer to completion and commission.',
  'Follow-ups': 'Stay in touch and never miss an important next action.',
  Viewings: 'Plan appointments, log feedback, and progress interested buyers.',
  Shortlist: 'Match opportunities with the right clients.',
  Payments: 'Track commission payments and outstanding receipts.',
  Expenses: 'Understand what you spend to grow your business.',
  'Interaction log': 'The full story behind every client conversation.',
  'Client care': 'Turn one successful transaction into a lasting relationship.',
};

const preferredCols = {
  Clients: [
    'Client ID',
    'Full name',
    'Lead stage',
    'Buy / rent',
    'Preferred communities',
    'Maximum budget AED',
    'Lead quality score / 100',
    'Next follow-up auto',
  ],
  Contacts: ['Contact ID', 'Full name', 'Contact type', 'Company', 'Phone', 'Email'],
  Properties: [
    'Property ID',
    'Listing title',
    'Community',
    'Property type',
    'Sale / rental',
    'Price / annual rent AED',
    'Listing status',
    'Ready / off-plan',
  ],
  Deals: [
    'Deal ID',
    'Client ID',
    'Property ID',
    'Deal stage',
    'Pipeline type',
    'Agreed value AED',
    'Your expected fee AED',
    'Next action due',
  ],
  'Follow-ups': ['Activity ID', 'Client ID', 'Next action', 'Due date', 'Task status', 'Channel'],
  Viewings: [
    'Viewing ID',
    'Client ID',
    'Property ID',
    'Appointment date & time',
    'Viewing status',
    'Next action',
  ],
  Shortlist: [
    'Match ID',
    'Client ID',
    'Property ID',
    'Date sent',
    'Client response',
    'Next action',
  ],
  'Interaction log': [
    'Log ID',
    'Client ID',
    'Contacted on UAE time',
    'Channel',
    'Conversation topic',
    'Next action',
    'Action status',
  ],
  'Client care': ['Care ID', 'Client ID', 'Touchpoint type', 'Next contact', 'Task status'],
  Payments: [
    'Payment ID',
    'Deal ID',
    'Receipt date',
    'Your fee received AED ex VAT',
    'Total received AED',
  ],
  Expenses: [
    'Expense ID',
    'Date paid',
    'Expense category',
    'Platform / supplier',
    'Amount paid AED',
  ],
};

export { nav, labels, descriptions, preferredCols };
